version: "2"
services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      # - "3000:3000"
      - "9090-9091:8080-8081"
    network_mode: "host"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: paulysun
  #     POSTGRES_DB: Zenisthebest1@
