version: "3.8"
services:
  web:
    build: ./
    command: npm start
    volumes:
      - .:/app/
      - /node_modules
    ports:
      # - "3000:3000"
      - "9090-9091:8080-8081"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: paulysun
  #     POSTGRES_DB: Zenisthebest1@
